version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.${ENV}  # Escolhe dev ou prod pelo .env
    container_name: api-pagamento-frete
    command: sh ./wait-for-db.sh db python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
