FROM python:3.11-slim

WORKDIR /code

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . /code/

CMD ["sh", "-c", "python manage.py migrate && gunicorn api_pagamento_frete.wsgi:application --bind 0.0.0.0:${PORT}"]